In [1]:
# arrays of zeros & ones
# arange
# empty
# identity
# transpose

import numpy as np


In [20]:
np.zeros((4,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
#  arange
# empty
# identity
# transpose

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [39]:
np.arange(10,-10,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6,
       -7, -8, -9])

In [60]:
# empty
np.empty(9)

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [51]:
# identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [56]:
# transpose -----> row ---> col
# col --- > rows

a = np.array([[34,45,67],[50,23,12],[67,76,41]])

In [57]:
a

array([[34, 45, 67],
       [90, 23, 12],
       [67, 76, 41]])

In [58]:
a.T

array([[34, 90, 67],
       [45, 23, 76],
       [67, 12, 41]])

In [74]:
# linspace
# min
# max
# sort
# sum
# argmin
# argmax
# argsort

np.linspace(1,11,4) 

array([ 1.        ,  4.33333333,  7.66666667, 11.        ])

In [81]:
a = np.array([[34,45,67],[50,23,12],[67,76,41]])

In [82]:
a

array([[34, 45, 67],
       [50, 23, 12],
       [67, 76, 41]])

In [77]:
a.max()

76

In [78]:
a.min()

12

In [79]:
a.sort()

In [80]:
a

array([[34, 45, 67],
       [12, 23, 50],
       [41, 67, 76]])

In [83]:
# argmin
# argmax
# argsort

a.argmax()

7

In [84]:
a

array([[34, 45, 67],
       [50, 23, 12],
       [67, 76, 41]])

In [85]:
a.argmin()

5

In [86]:
a.argsort()

array([[0, 1, 2],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [87]:
# sum
a.sum()

415

In [88]:
# row wise axis = 1
# col wise axis = 0

a


array([[34, 45, 67],
       [50, 23, 12],
       [67, 76, 41]])

In [89]:
a.sum(axis = 0)

array([151, 144, 120])

In [90]:
a.sum(axis = 1)

array([146,  85, 184])