In [4]:
import numpy as np

In [5]:
#array----> to make array 1D,2D,3D array.

arr = np.array([1,2,3,4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [9]:
# shape & size
arr.shape

(4,)

In [10]:
arr.size

4

In [11]:
# 2d array

arr = np.array([[1,2,3],[4,5,6]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr.ndim

2

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(2, 3)

In [16]:
#wap to print an array of (3,2) matrix.

arr = np.array([[1,2],[3,4],[5,6]])

In [17]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
arr.shape

(3, 2)

In [19]:
# 3d matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a.ndim

2

In [26]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [27]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [28]:
arr.ndim

3

In [34]:
a = np.array([[145,-52,300]])
b = np.array([[[1,2,3]]])
c = a+b
print(c)

[[[146 -50 303]]]


In [35]:
# slicing & indexing
a = np.array([[[34,56,78],[45,67,90],[23,27,9]]])

In [36]:
a

array([[[34, 56, 78],
        [45, 67, 90],
        [23, 27,  9]]])

In [41]:
a[0][1][1]

67